### ISSUE TITLE
Works with VAIO All in one VPCL11M1E

### ISSUE THREAD

**Issue by devkicks** [glorang/nwfermi#1]
First of all, many thanks for putting down the guide. I was able to make this work with Sony Vaio VPCL11M1E which shows up as: "Bus 005 Device 002: ID 1926:0065 NextWindow 1950 HID Touchscreen".

Leaving this for anyone who visits this in future.

**Comment by glorang** [comment]
Cool, thanks! Glad it was useful. I've updated the README page with your confirmation.

**Comment by friscodelrosario** [comment]
Confirmation for HP TouchSmart 520-1047c
Bus 002 Device 006: ID 1926:0dbe NextWindow

Linux 5.4.0-65-generic #73~18.04.1-Ubuntu
