### ISSUE TITLE
Some suggestions for updating the installation instructions

### ISSUE THREAD

**Issue by ayubowan2u** [glorang/nwfermi#10]
Firstly, thank you very much for this code and instructions.

Perhaps you may want to consider adding the following to your instructions.

1. cloning using the command 'git clone github@github.com/glorang/nwfermi.git (I had wrong syntax for this and spent hours trying to work it out and someone on the forum kindly pointed it out to me)
2. change directory to the nwfermi directory before copying the source file.

Once again, thanks very much for your brilliant work.

**Comment by glorang** [comment]
In your case it was probably a lot easier to download all files as a zip from this repo. You can do this via the green "Code" button on the front page and select "Download ZIP".

I've now added a chapter `Get source files from this Git repo` in the installation procedure to clarify the installation instructions.

Cheers,
Geert
