### ISSUE TITLE
Touchscreen not working

### ISSUE THREAD

**Issue by Rolol0ko** [glorang/nwfermi#3]
I followed all of the steps, I don't think there was any issues, but it doesn't work. I don't even really know how to check if it's installed. is there any way to verify that I have correctly installed it? I think I did all the steps then rebooted, there were no steps after that, but it does not work.

nwfermi_daemon is present in /usr/sbin

lsusb gives:
Bus 003 Device 007: ID 1926:0dbe NextWindow Touchscreen

I think I did all the steps then rebooted, there were no steps after that, but it does not work.

Thanks!

**Comment by Rolol0ko** [comment]
`user@debian:~$ evtest
No device specified, trying to scan all of /dev/input/event*
Not running as root, no devices may be available.
Available devices:
/dev/input/event0:      AT Raw Set 2 keyboard
/dev/input/event1:      Power Button
/dev/input/event2:      Power Button
/dev/input/event3:      Video Bus
/dev/input/event4:      Cyber Acoustics CVL-2009
/dev/input/event5:      Logitech M585/M590
/dev/input/event6:      Logitech K850
/dev/input/event7:      PC Speaker
/dev/input/event8:      Nextwindow Fermi Touchscreen
/dev/input/event9:      HP High Definition 1MP Webcam: 
/dev/input/event10:     HDA Digital PCBeep
/dev/input/event11:     HDA Intel PCH Mic
/dev/input/event12:     HDA Intel PCH Line Out
/dev/input/event13:     HDA Intel PCH Headphone
Select the device event number [0-13]: 8
Input driver version is 1.0.1
Input device ID: bus 0x0 vendor 0x0 product 0x0 version 0x0
Input device name: "Nextwindow Fermi Touchscreen"
Supported events:
  Event type 0 (EV_SYN)
  Event type 1 (EV_KEY)
    Event code 261 (BTN_5)
    Event code 272 (BTN_LEFT)
    Event code 273 (BTN_RIGHT)
  Event type 3 (EV_ABS)
    Event code 0 (ABS_X)
      Value      0
      Min        0
      Max    32767
    Event code 1 (ABS_Y)
      Value      0
      Min        0
      Max    32767
    Event code 48 (ABS_MT_TOUCH_MAJOR)
      Value      0
      Min        0
      Max    32767
    Event code 49 (ABS_MT_TOUCH_MINOR)
      Value      0
      Min        0
      Max    32767
    Event code 53 (ABS_MT_POSITION_X)
      Value      0
      Min        0
      Max    32767
    Event code 54 (ABS_MT_POSITION_Y)
      Value      0
      Min        0
      Max    32767
    Event code 57 (ABS_MT_TRACKING_ID)
      Value      0
      Min        0
      Max      255
Properties:
Testing ... (interrupt to exit)`

`user@debian:~$ ps
    PID TTY          TIME CMD
   2066 pts/3    00:00:00 bash
   3094 pts/3    00:00:00 ps`

How would I start the daemon?

I am somewhat new to linux, so I am not really sure exactly what you want me to do/if i did what you asked right.

**Comment by glorang** [comment]
You should run `evtest /dev/input/event8` and then touch the screen to see if any events are generated.

The "full" `ps` would be `ps faux |grep nwfermi`

**Comment by Rolol0ko** [comment]
```
debian:~$ evtest /dev/input/event8
Input driver version is 1.0.1
Input device ID: bus 0x1 vendor 0x111d product 0x76e0 version 0x1
Input device name: "HDA Digital PCBeep"
Supported events:
  Event type 0 (EV_SYN)
  Event type 18 (EV_SND)
    Event code 1 (SND_BELL) state 0
    Event code 2 (SND_TONE) state 0
Properties:
Testing ... (interrupt to exit)
```
There were no events being generated.


```
debian:~ps faux |grep nwfermimi
ronan       1711  0.0  0.0   6180   656 pts/1    S+   08:32   0:00          \_ grep nwfermi
```

Sorry for delay.

**Comment by glorang** [comment]
You are using the wrong input device now, it should be the one that lists `Nextwindow Fermi Touchscreen` and not `HDA Digital PCBeep`

Also the daemon is not running so it will definitely not work. 

Please make sure all steps of the procedure were done successfully, execute them again and look carefully at the output.
I can try to help you here but it's probably a lot more efficient if you try to find someone more experienced with Linux locally.

**Comment by glorang** [comment]
I've released a new procedure that will install nwfermi v7 based on a more recent HP driver compared to latest v6 that was available in Ubuntu Launchpad.

I'll close this for now but feel free to open a new issue after you attempted the new procedure to install v7.
