### ISSUE TITLE
Failures to create device for /dev/input/js0 and /dev/input/mouse

### ISSUE THREAD

**Issue by friscodelrosario** [glorang/nwfermi#6]
Hm. What now?!

^Cfrisco@frisco-520-1047c:~grep -i fermi /home/frisco/.local/share/xorg/Xorg.1.log
[   163.490] (II) config/udev: Adding input device Nextwindow Fermi Touchscreen (/dev/input/event12)
[   163.490] (**) Nextwindow Fermi Touchscreen: Applying InputClass "libinput pointer catchall"
[   163.490] (**) Nextwindow Fermi Touchscreen: Applying InputClass "Nextwindow Fermi Touchscreen"
[   163.490] (II) Using input driver 'libinput' for 'Nextwindow Fermi Touchscreen'
[   163.491] (**) Nextwindow Fermi Touchscreen: always reports core events
[   163.491] (II) event12 - Nextwindow Fermi Touchscreen: is tagged by udev as: Mouse
[   163.492] (II) event12 - Nextwindow Fermi Touchscreen: device is a pointer
[   163.492] (II) event12 - Nextwindow Fermi Touchscreen: device removed
[   163.492] (II) XINPUT: Adding extended input device "Nextwindow Fermi Touchscreen" (type: MOUSE, id 19)
[   163.492] (**) Nextwindow Fermi Touchscreen: (accel) selected scheme none/0
[   163.492] (**) Nextwindow Fermi Touchscreen: (accel) acceleration factor: 2.000
[   163.492] (**) Nextwindow Fermi Touchscreen: (accel) acceleration threshold: 4
[   163.493] (II) event12 - Nextwindow Fermi Touchscreen: is tagged by udev as: Mouse
[   163.493] (II) event12 - Nextwindow Fermi Touchscreen: device is a pointer
[   163.494] (II) config/udev: Adding input device Nextwindow Fermi Touchscreen (/dev/input/js0)
[   163.494] (**) Nextwindow Fermi Touchscreen: Applying InputClass "Nextwindow Fermi Touchscreen"
[   163.494] (II) Using input driver 'libinput' for 'Nextwindow Fermi Touchscreen'
[   163.495] (**) Nextwindow Fermi Touchscreen: always reports core events
[   163.541] (EE) libinput: Nextwindow Fermi Touchscreen: Failed to create a device for /dev/input/js0
[   163.541] (EE) PreInit returned 2 for "Nextwindow Fermi Touchscreen"
[   163.541] (II) config/udev: Adding input device Nextwindow Fermi Touchscreen (/dev/input/mouse3)
[   163.541] (**) Nextwindow Fermi Touchscreen: Applying InputClass "Nextwindow Fermi Touchscreen"
[   163.542] (II) Using input driver 'libinput' for 'Nextwindow Fermi Touchscreen'
[   163.542] (**) Nextwindow Fermi Touchscreen: always reports core events
[   163.585] (EE) libinput: Nextwindow Fermi Touchscreen: Failed to create a device for /dev/input/mouse3
[   163.585] (EE) PreInit returned 2 for "Nextwindow Fermi Touchscreen"

**Comment by glorang** [comment]
It's not using the `nextwindow` driver as it should:

```
[ 163.490] (II) Using input driver 'libinput' for 'Nextwindow Fermi Touchscreen'
```

Best to check the debug steps as listed in the Debugging chapter. Perhaps you got a kernel update recently and the module failed to build or did not build at all?

**Comment by friscodelrosario** [comment]
I uninstalled and removed the module (unbuild is no longer in the menu; perhaps the doc should reflect that), rebuilt and reinstalled.

This is more like it, right?

$ grep -i fermi /home/frisco/.local/share/xorg/Xorg.1.log
[   988.216] (II) config/udev: Adding input device Nextwindow Fermi Touchscreen (/dev/input/event12)
[   988.216] (**) Nextwindow Fermi Touchscreen: Applying InputClass "libinput pointer catchall"
[   988.216] (**) Nextwindow Fermi Touchscreen: Applying InputClass "Nextwindow Fermi Touchscreen"
[   988.216] (II) Using input driver 'nextwindow' for 'Nextwindow Fermi Touchscreen'
[   988.216] (**) Nextwindow Fermi Touchscreen: always reports core events
[   988.216] (**) Nextwindow Fermi Touchscreen: always reports core events
[   988.216] (II) Nextwindow Fermi Touchscreen: Using device /dev/input/event12.
[   988.216] (II) Nextwindow Fermi Touchscreen: Using touch help.
[   988.249] (II) XINPUT: Adding extended input device "Nextwindow Fermi Touchscreen" (type: UNKNOWN, id 19)
[   988.249] (**) Nextwindow Fermi Touchscreen: (accel) keeping acceleration scheme 1
[   988.249] (**) Nextwindow Fermi Touchscreen: (accel) acceleration profile 0
[   988.249] (**) Nextwindow Fermi Touchscreen: (accel) acceleration factor: 2.000
[   988.249] (**) Nextwindow Fermi Touchscreen: (accel) acceleration threshold: 4
[   988.249] (II) Nextwindow Fermi Touchscreen: On.
[   988.249] (II) config/udev: Adding input device Nextwindow Fermi Touchscreen (/dev/input/js0)
[   988.249] (**) Nextwindow Fermi Touchscreen: Applying InputClass "Nextwindow Fermi Touchscreen"
[   988.249] (II) Using input driver 'nextwindow' for 'Nextwindow Fermi Touchscreen'
[   988.249] (**) Nextwindow Fermi Touchscreen: always reports core events
[   988.249] (**) Nextwindow Fermi Touchscreen: always reports core events
[   988.249] (II) Nextwindow Fermi Touchscreen: Using device /dev/input/js0.
[   988.249] (II) Nextwindow Fermi Touchscreen: Using touch help.
[   988.285] (II) XINPUT: Adding extended input device "Nextwindow Fermi Touchscreen" (type: UNKNOWN, id 20)
[   988.285] (**) Nextwindow Fermi Touchscreen: (accel) keeping acceleration scheme 1
[   988.285] (**) Nextwindow Fermi Touchscreen: (accel) acceleration profile 0
[   988.285] (**) Nextwindow Fermi Touchscreen: (accel) acceleration factor: 2.000
[   988.285] (**) Nextwindow Fermi Touchscreen: (accel) acceleration threshold: 4
[   988.285] (II) Nextwindow Fermi Touchscreen: On.
[   988.285] (II) config/udev: Adding input device Nextwindow Fermi Touchscreen (/dev/input/mouse3)
[   988.285] (**) Nextwindow Fermi Touchscreen: Applying InputClass "Nextwindow Fermi Touchscreen"
[   988.285] (II) Using input driver 'nextwindow' for 'Nextwindow Fermi Touchscreen'
[   988.285] (**) Nextwindow Fermi Touchscreen: always reports core events
[   988.285] (**) Nextwindow Fermi Touchscreen: always reports core events
[   988.285] (II) Nextwindow Fermi Touchscreen: Using device /dev/input/mouse3.
[   988.285] (II) Nextwindow Fermi Touchscreen: Using touch help.
[   988.321] (II) XINPUT: Adding extended input device "Nextwindow Fermi Touchscreen" (type: UNKNOWN, id 21)
[   988.321] (**) Nextwindow Fermi Touchscreen: (accel) keeping acceleration scheme 1
[   988.321] (**) Nextwindow Fermi Touchscreen: (accel) acceleration profile 0
[   988.321] (**) Nextwindow Fermi Touchscreen: (accel) acceleration factor: 2.000
[   988.321] (**) Nextwindow Fermi Touchscreen: (accel) acceleration threshold: 4
[   988.321] (II) Nextwindow Fermi Touchscreen: On.

Still no go.

Then I logged out of XFCE and back into GNOME. Back in business.

Thanks again.

**Comment by friscodelrosario** [comment]
Working again in XFCE, too. Go figure.
