### ISSUE TITLE
Simple question

### ISSUE THREAD

**Issue by mouchon** [glorang/nwfermi#9]
Have an issue with double click, it seems not to work. Does there is special option to place in the xorg.conf file ?

Thanks

**Comment by glorang** [comment]
Can you run `evtest` and check if it registers 2 events ? 

What exactly is the use case for double click on a touchscreen ?

**Comment by mouchon** [comment]
Sorry it, works, in fact the issue is KDE for which probably delay between the event is not good
I use the double click in a web application to remove an item from a list.
thanks .
